### PR TITLE
Mega PR

### PR DESCRIPTION
**Pull request by hangocdinhnew**
Fixes things, update README.MD, remove garbage, and etc.

### CODE REVIEW

**Comment by hangocdinhnew** [comment]
Note: This PR contains few of my works, there are lots of PR, issue, I follow through that step by step to fixes things so thanks to all the one who commited the issue and the PRs, and please again remember that this is not all my work.

**Comment by hangocdinhnew** [comment]
And there's some conflicting things so be aware, also I removed yay and replaced it with paru, if this is an issue I would like to help, so write in the comment.

**Comment by arnavgr** [comment]
> Note: This PR contains few of my works, there are lots of PR, issue, I follow through that step by step to fixes things so thanks to all the one who commited the issue and the PRs, and please again remember that this is not all my work.

why dont you just maintain your own fork instead of adding your stuff to this repo

**Comment by hangocdinhnew** [comment]
@arnavgr This is why I closed this.

**Pull request closed without merging**
